### ISSUE TITLE
openssl `[.key` method breaks hash_lookup_helper

### ISSUE THREAD

**Issue by ray-p144** [trinker/qdapTools#8]
I saw on [stackoverflow](https://stackoverflow.com/questions/45197158/how-to-avoid-class-name-conflict-with-a-package-loaded-via-a-namespace-and-not) that the issue with the `openssl` package's `[[.key` method was fixed but it looks like the `openssl` package's `[.key` method is also causing issues. 

On this line: https://github.com/trinker/qdapTools/blob/ce2fde21b3108fa454aaa01f64fdc71d6bb222e9/R/hash.R#L141

R is attempting to use the `[.key` method rather than the `[.data.table` method. 

Reproducible example:
```
library(data.table)
library(qdap)
library(openssl)
polarity(c("easy day", "hard day"), c("a", "b"))
# Error in derive_pubkey(key) : 
#   RAW() can only be applied to a 'raw', not a 'list'
```
Forcing R to see the `key` object as a `data.table` works. (The following code was just to test the `[.data.table` method, and is not meant to be a suggested fix).
```
 
assignInNamespace(
  x = "hash_lookup_helper",
  value = function(terms, key, missing = NA) {
    
    terms <- data.frame(x=terms, stringsAsFactors = FALSE)
    setDT(terms)
    
    out <- data.table::as.data.table(key)[terms][[2]]
    
    if (!is.null(missing) && is.na(missing)) return(out)
    if (!is.null(missing) && !is.na(missing)) {
      hits <- which(is.na(out))
      out[hits] <- missing
      return(out)
    }
    
    if (is.null(missing)) {
      hits <- which(is.na(out))
      out[hits] <- terms[[1]][hits]
      return(out)
    }
    
  },
  ns = "qdapTools"
)

polarity(c("easy day", "hard day"), c("a", "b"))
#   b total.sentences total.words ave.polarity sd.polarity stan.mean.polarity
# 1 a               1           2        0.707          NA                 NA
# 2 b               1           2       -0.707          NA                 NA

```

**Comment by trinker** [comment]
Thanks for the heads up.  Much appreciated.  We'll have a look and adjust accordingly.

**Comment by trinker** [comment]
Commit #https://github.com/trinker/qdapTools/commit/34cc3f26295b968550553fd26d74bfd970457796 solves this thank you for bringing this to our attention
